In [24]:
import tensorflow as tf

# 1. 导入数据集 mnist
from tensorflow.keras.datasets import mnist

# 2. 从 layer 模块导入 Dense 和 Activation
from tensorflow.keras.layers import Dense, Activation

# 3. 从 optimizers 模块导入 SGD
from tensorflow.keras.optimizers import SGD
# 或者使用旧版本路径，以防兼容性问题
# from tensorflow.keras.optimizers.legacy import SGD

# 4. 从 utils 模块导入 np_utils
from tensorflow.keras.utils import to_categorical as np_utils

In [25]:
print("--- 1. 加载 MNIST 数据集 ---")

# 使用mnist模块的load_data方法加载数据集
# 它会将数据自动解包到训练集和测试集的特征/标签变量中
(X_train, y_train), (X_test, y_test) = mnist.load_data()

print("\n--- 2. 查看四个变量的维度 (Shape) ---")

# 检查训练集特征 (X_train) 的维度
print(f"X_train (训练集特征) 维度: {X_train.shape}")

# 检查训练集标签 (y_train) 的维度
print(f"y_train (训练集标签) 维度: {y_train.shape}")

# 检查测试集特征 (X_test) 的维度
print(f"X_test (测试集特征) 维度: {X_test.shape}")

# 检查测试集标签 (y_test) 的维度
# 注意：您的要求是 (X_test, yest)，但正确变量名应该是 y_test
print(f"y_test (测试集标签) 维度: {y_test.shape}")

print("\n--- 3. 维度说明 ---")
print("维度正确性验证:")
print(f"* 训练集图像数量: {X_train.shape[0]} 张")
print(f"* 测试集图像数量: {X_test.shape[0]} 张")
print(f"* 图像尺寸: {X_train.shape[1]} 像素 x {X_train.shape[2]} 像素 (28x28)")

--- 1. 加载 MNIST 数据集 ---

--- 2. 查看四个变量的维度 (Shape) ---
X_train (训练集特征) 维度: (60000, 28, 28)
y_train (训练集标签) 维度: (60000,)
X_test (测试集特征) 维度: (10000, 28, 28)
y_test (测试集标签) 维度: (10000,)

--- 3. 维度说明 ---
维度正确性验证:
* 训练集图像数量: 60000 张
* 测试集图像数量: 10000 张
* 图像尺寸: 28 像素 x 28 像素 (28x28)


In [26]:
# 假设 X_train 和 X_test 已经从上一步加载并拥有正确的初始形状 (60000, 28, 28) 和 (10000, 28, 28)

# ----------------------------------------------------
# 步骤 1: 展平 (Reshape) 数据
# ----------------------------------------------------
# X_train 形状从 60000x28x28 变为 60000x784 (28*28=784)
X_train = X_train.reshape(60000, 784)

# X_test 形状从 10000x28x28 变为 10000x784
X_test = X_test.reshape(10000, 784)

print("--- 1. 数据展平后的形状检查 ---")
print(f"X_train 展平后的形状: {X_train.shape}")
print(f"X_test 展平后的形状: {X_test.shape}")


# ----------------------------------------------------
# 步骤 2: 转换数据类型 (astype)
# ----------------------------------------------------
# 将元素的默认数据类型（通常是 uint8）改为 float32
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

# ----------------------------------------------------
# 步骤 3: 验证形状和数据类型
# ----------------------------------------------------
print("\n--- 2. 最终形状和数据类型验证 ---")

# 验证 X_train 的形状和数据类型
print("X_train 最终验证:")
print(f"  形状 (Shape): {X_train.shape}")
print(f"  数据类型 (dtype): {X_train.dtype}")

# 验证 X_test 的形状和数据类型
print("X_test 最终验证:")
print(f"  形状 (Shape): {X_test.shape}")
print(f"  数据类型 (dtype): {X_test.dtype}")

--- 1. 数据展平后的形状检查 ---
X_train 展平后的形状: (60000, 784)
X_test 展平后的形状: (10000, 784)

--- 2. 最终形状和数据类型验证 ---
X_train 最终验证:
  形状 (Shape): (60000, 784)
  数据类型 (dtype): float32
X_test 最终验证:
  形状 (Shape): (10000, 784)
  数据类型 (dtype): float32


In [27]:
# 假设 X_train 和 X_test 已经从上一步展平并转换为了 float32 类型

print("--- 1. 执行特征归一化 (Normalization) ---")

# 归一化操作：将所有像素值除以 255.0
# 因为 X_train 和 X_test 已经是 float32 类型，可以直接进行浮点除法
X_train /= 255.0
X_test /= 255.0

print("归一化完成：像素值已缩放到 0.0 到 1.0 之间。")


# ----------------------------------------------------
# 步骤 2: 查看 X_train 归一化后的部分值进行验证
# ----------------------------------------------------
print("\n--- 2. 检查 X_train 归一化后的第 2 个例子 (索引 1) 的部分像素值 ---")

# 查看 X_train 的第 2 个例子（索引为 1）的第 100 个到第 150 个像素点的值
# X_train[1] 代表第 2 个例子
# X_train[1][99:150] 代表其第 100 个到第 150 个像素点（Python 索引从 0 开始，所以是 99 到 150）
print(X_train[1][99:150])

--- 1. 执行特征归一化 (Normalization) ---
归一化完成：像素值已缩放到 0.0 到 1.0 之间。

--- 2. 检查 X_train 归一化后的第 2 个例子 (索引 1) 的部分像素值 ---
[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.2        0.62352943
 0.99215686 0.62352943 0.19607843 0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.        ]


In [28]:
# 导入 to_categorical 方法
from tensorflow.keras.utils import to_categorical

print("--- 1. 执行 One-Hot 编码 ---")

# MNIST 数据集的类别总数是 0 到 9，共 10 个类别。
NUM_CLASSES = 10

# 对训练集标签进行 One-Hot 编码
Y_train = to_categorical(y_train, num_classes=NUM_CLASSES)

# 对测试集标签进行 One-Hot 编码
Y_test = to_categorical(y_test, num_classes=NUM_CLASSES)

print("One-Hot 编码完成。")


# ----------------------------------------------------
# 步骤 2: 打印 Y_train 前五行进行验证
# ----------------------------------------------------
print("\n--- 2. 检查 Y_train 前五行的 One-Hot 编码结果 ---")

# 打印 Y_train 编码后的前五行
print(Y_train[:5])

--- 1. 执行 One-Hot 编码 ---
One-Hot 编码完成。

--- 2. 检查 Y_train 前五行的 One-Hot 编码结果 ---
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [29]:
# 导入所需的模块
from tensorflow.keras.models import Sequential

print("--- 1. 创建序列模型对象 ---")

# 1. 创建一个序列模型对象 model
model = Sequential()

print("模型对象创建成功。")


print("\n--- 2. 添加全连接层 (Dense) 和激活层 (Activation) ---")

# 2. 添加全连接层 (Dense)
# 输出维度 (units) 是 10 (对应 10 个类别)
# 输入维度 (input_shape) 是 784 (对应展平后的图像像素数)
model.add(Dense(
    units=10, 
    input_shape=(784,)  # 指定第一层的输入形状
))

# 3. 添加激活层 (Activation)
# 在输出层使用 'softmax' 激活函数，适用于多分类问题
model.add(Activation('softmax'))

print("全连接层和激活层添加成功。")


print("\n--- 3. 查看模型摘要 (Summary) ---")

# 4. 通过 model.summary() 查看模型结构和参数数量
model.summary()

--- 1. 创建序列模型对象 ---
模型对象创建成功。

--- 2. 添加全连接层 (Dense) 和激活层 (Activation) ---
全连接层和激活层添加成功。

--- 3. 查看模型摘要 (Summary) ---
Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 10)                7850      
                                                                 
 activation_1 (Activation)   (None, 10)                0         
                                                                 
Total params: 7,850
Trainable params: 7,850
Non-trainable params: 0
_________________________________________________________________


In [30]:
# 从 metrics 模块导入 Precision 和 Recall 类
from tensorflow.keras.metrics import Precision, Recall

print("--- 1. 定义优化器和指标 ---")

sgd_optimizer = SGD() 

# 创建一个包含多个指标的列表
custom_metrics = [
    'accuracy',       # 默认的准确率 (CategoricalAccuracy 的简写)
    Precision(),      # 精确率 (使用类的形式)
    Recall()          # 召回率 (使用类的形式)
]


print("\n--- 2. 编译模型 (Compile) ---")

# 编译模型，将指标列表传递给 metrics 参数
model.compile(
    # 损失函数: 适用于 One-Hot 编码标签的多分类任务
    loss='categorical_crossentropy', 
    
    # 优化器: 使用实例化好的 SGD 优化器对象
    optimizer=sgd_optimizer,
    
    # 评估指标: 使用包含多个指标的列表
    metrics=custom_metrics
)

print("模型编译完成！")
print(f"使用的损失函数 (Loss): categorical_crossentropy")
print(f"使用的优化器 (Optimizer): SGD")
print(f"使用的评估指标 (Metrics): {custom_metrics}")

--- 1. 定义优化器和指标 ---

--- 2. 编译模型 (Compile) ---
模型编译完成！
使用的损失函数 (Loss): categorical_crossentropy
使用的优化器 (Optimizer): SGD
使用的评估指标 (Metrics): ['accuracy', <keras.metrics.metrics.Precision object at 0x000001E8A7FD22B0>, <keras.metrics.metrics.Recall object at 0x000001E8A7FC3370>]


In [31]:
# 假设 model, X_train, Y_train 变量已准备就绪

print("--- 1. 开始训练神经网络模型 (model.fit) ---")

# 调用 fit 方法训练模型
# 训练过程的结果将存储在 history 对象中
history = model.fit(
    x=X_train,              # 输入数据（特征）
    y=Y_train,              # 标签数据（已 One-Hot 编码）
    batch_size=128,         # 每次梯度下降使用的样本数
    epochs=200,             # 总共训练的轮次
    verbose=1,              # 以进度条形式输出日志信息
    validation_split=0.2    # 从 X_train/Y_train 中划分 20% 作为验证集
)

print("\n--- 训练完成！ ---")

--- 1. 开始训练神经网络模型 (model.fit) ---
Epoch 1/200
375/375 [==============================] - 5s 10ms/step - loss: 1.4055 - accuracy: 0.6460 - precision: 0.9872 - recall: 0.1657 - val_loss: 0.9011 - val_accuracy: 0.8206 - val_precision: 0.9837 - val_recall: 0.4482
Epoch 2/200
375/375 [==============================] - 4s 10ms/step - loss: 0.7981 - accuracy: 0.8236 - precision: 0.9699 - recall: 0.5492 - val_loss: 0.6605 - val_accuracy: 0.8556 - val_precision: 0.9701 - val_recall: 0.6680
Epoch 3/200
375/375 [==============================] - 3s 8ms/step - loss: 0.6459 - accuracy: 0.8488 - precision: 0.9591 - recall: 0.6758 - val_loss: 0.5638 - val_accuracy: 0.8683 - val_precision: 0.9631 - val_recall: 0.7360
Epoch 4/200
375/375 [==============================] - 3s 9ms/step - loss: 0.5725 - accuracy: 0.8610 - precision: 0.9528 - recall: 0.7318 - val_loss: 0.5103 - val_accuracy: 0.8765 - val_precision: 0.9582 - val_recall: 0.7712
Epoch 5/200
375/375 [==============================] - 4s 10ms/s

In [32]:
# 假设 model 对象已训练完成，且 X_test, Y_test 已准备就绪

print("--- 1. 使用 model.evaluate 在测试集上评估模型 ---")

# 1) 使用 model 对象的 evaluate 方法来评估模型
# x 和 y 分别传入测试集特征和标签
# verbose=1 会显示评估过程的进度条
score = model.evaluate(
    x=X_test, 
    y=Y_test, 
    verbose=1
)

print("\n--- 2. 打印评估结果 (Score) ---")

# evaluate 方法返回一个包含损失值和所有评估指标的列表。
# 顺序对应于您在 model.compile 中 metrics=['loss', 'accuracy', ...] 的顺序。

# 假设我们在编译时 metrics=['accuracy', Precision(), Recall()]
# score[0] 是损失值 (loss)
# score[1] 是准确率 (accuracy)

# 2) 打印 score 的第一项和第二项值
print("总损失值 (Loss):", score[0])
print("准确率 (Accuracy):", score[1])
print("精确率 (Precision):", score[2])
print("召回率 (Recall):", score[3])

--- 1. 使用 model.evaluate 在测试集上评估模型 ---
313/313 [==============================] - 0s 862us/step - loss: 0.2778 - accuracy: 0.9221 - precision: 0.9414 - recall: 0.9047

--- 2. 打印评估结果 (Score) ---
总损失值 (Loss): 0.27784493565559387
准确率 (Accuracy): 0.9221000075340271
精确率 (Precision): 0.9414151906967163
召回率 (Recall): 0.904699981212616
